name: Trigger Deploy to Branch Preview Web Slot

stages:
  - stage: Build
    displayName: Trigger Preview Slot Web Deployment
    jobs:
    - job: Build
      steps:
        - checkout: none
        - bash: echo Build.SourceBranch = $(Build.SourceBranch) # outputs refs/heads/main
        - bash: echo Build.Reason = $(Build.Reason) # outputs IndividualCI
        - bash: echo Trigger Deploy to $(System.PullRequest.SourceBranch) Web Slot