name: Trigger Deploy to Preview Web Slot
variables:
  system.debug: true
stages:
  - stage: Build
    displayName: Trigger Preview Slot Creation and Web Deployment
    jobs:
    - job: Build
      steps:
        - checkout: none
        - bash: echo Trigger Deploy to $(System.PullRequest.SourceBranch) Web Slot
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              B64_PAT=$(printf ":$(System.AccessToken)" | base64)  
              echo 'Hello world'
              echo "PAT: $(B64_PAT)"
