name: Trigger Deploy to Preview Web Slot
variables:
  system.debug: true
stages:
  - stage: Build
    displayName: Trigger Preview Slot Creation and Web Deployment
    jobs:
    - job: Build
      steps:
        - checkout: none
        - bash: echo Trigger Deploy to $(System.PullRequest.SourceBranch) Web Slot
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              B64_PAT=$(printf ":$(System.AccessToken)" | base64)  
              echo "Authorization: Bearer $(System.AccessToken)"
              curl -L -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer $(System.AccessToken)" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/Azure/arc_jumpstart_docs/pullrequests/$(System.PullRequest.PullRequestId)/comments
              if [[ $(System.PullRequest.SourceBranch) =~ [^a-zA-Z0-9_-] ]]; then
                echo "Branch names cannot contain special characters. Please rename the branch and try again."
                exit 1
              else
                echo ""
              fi
              exit 1
