name: Trigger Deploy to Preview Web Slot
variables:
  system.debug: true
stages:
  - stage: Build
    displayName: Trigger Preview Slot Creation and Web Deployment
    jobs:
    - job: CheckErrors
      displayName: Check if the PR name is correct
      steps:
        - checkout: none
        - bash: |
              if [[ $(System.PullRequest.SourceBranch) =~ [^a-zA-Z0-9_-] ]]; then
                echo "Branch names cannot contain special characters. Please rename the branch and try again."
                customMessage = 'Branch names cannot contain special characters. Please rename the branch and try again.'
                echo "##vso[task.setvariable variable=message;isOutput=true]$customMessage"
                echo "##vso[task.setvariable variable=error;isOutput=true]Yes"
              else
                echo "Deploying a new slot for this branch. This will take 5-10 minutes. Preview URL: https://$(System.PullRequest.PullRequestId)-pr-arcjumpstart.azurewebsites.net"
                customMessage = 'Deploying a new slot for this branch. This will take 5-10 minutes. Preview URL: https://$(System.PullRequest.PullRequestId)-pr-arcjumpstart.azurewebsites.net'
                echo "##vso[task.setvariable variable=message;isOutput=true]$customMessage"
                echo "##vso[task.setvariable variable=error;isOutput=true]No"
              fi
          name: SetMessage
    
    - job: CommentPR
      displayName: Check if the PR name is correct
      dependsOn: CheckErrors
      variables:
        message: $[ dependencies.CheckErrors.outputs['SetMessage.message'] ]
        error: $[ dependencies.CheckErrors.outputs['SetMessage.error'] ]
      steps:
        - task: GitHubComment@0
          inputs:
            gitHubConnection: 'Azure'
            repositoryName: 'Azure/arc_jumpstart_docs'
            comment: "$(message)"

        - bash: if [ "$(error)" == "Yes" ]; then exit 0 else exit 1 fi
          name : Exit