name: Trigger Deploy to Preview Web Slot
variables:
  system.debug: true
stages:
  - stage: Build
    displayName: Trigger Preview Slot Creation and Web Deployment
    jobs:
    - job: Build
      steps:
        - checkout: none
        - bash: echo $(INPUT_GITHUBCONNECTION)
        - powershell: Write-Host ($env:var1).substring(0,1) + ($env:var1).substring(1)
          displayName: DEBUG - print access token for local debugging
          env:
            var1: $(INPUT_GITHUBCONNECTION)
