name: Trigger Deploy to Preview Web Slot
variables:
  system.debug: true
stages:
  - stage: Build
    displayName: Trigger Preview Slot Creation and Web Deployment
    jobs:
    - job: Build
      steps:
        - checkout: none
        -
- task: GitHubComment@0
  inputs:
    gitHubConnection: 'Azure'
    repositoryName: 'Azure/arc_jumpstart_docs'
    comment: 'Hello World'