name: Trigger Deploy to Branch Preview Web Slot

stages:
  - stage: Build
    displayName: Trigger Preview Slot Web Deployment
    jobs:
    - job: Build
      steps:
        - checkout: none
        - bash: echo Trigger Deploy to $(System.PullRequest.SourceBranch) Web Slot