name: Trigger Deploy to Branch Preview Web Slot

pr:
  branches:
    include:
    - canary
    exclude:
      - main

variables:
- name: branch_name
  value: $(System.PullRequest.SourceBranch)
- name: branch_test
  value: Hola

stages:
  - stage: Build
    displayName: Trigger Preview Slot Web Deployment
    jobs:
    - job: Build
      steps:
        - checkout: none
        - bash: echo Trigger Deploy to $(branch_name) or $(branch_test) Web Slot