name: Trigger Deploy to Preview Web Slot

stages:
  - stage: Build
    displayName: Trigger Preview Slot Creation and Web Deployment
    jobs:
    - job: Build
      steps:
        - checkout: none
        - bash: echo Trigger Deploy to $(System.PullRequest.SourceBranch) Web Slot
        - script: |
              if [[ $(System.PullRequest.SourceBranch) =~ [^a-zA-Z0-9_-] ]]; then
                echo "Branch names cannot contain special characters. Please rename the branch and try again."
                curl -X POST -H "Authorization: Bearer $(System.AccessToken)" -H "Content-Type: application/json" -d '{"text": "Branch names cannot contain special characters. Please rename the branch and try again."}' "$(System.CollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.ID)/pullrequests/$(System.PullRequest.PullRequestId)/threads?api-version=5.0-preview.1"
                exit 1
              else
                echo "Deploying a new slot for this branch. This will take 5-10 minutes. Preview URL: https://pr-arcjumpstart.azurewebsites.net"
              fi