name: Canry push trigger Deploy to Canary Web Slot

resources:
  repositories:
  - repository: ArcJumpstartWeb
    type: github
    endpoint: ado-github-serviceConnection
    name: arc_jumpstart_web
    ref: master

trigger:
  branches:
    include:
    - canary

stages:
  - stage: Trigger
    displayName: Trigger Web Deployment
    jobs:
    - job: Trigger
      steps:
        - checkout: none
        - bash: echo Trigger Deploy to Canary Web Slot
        - template: 