name: Canry push trigger Deploy to Canary Web Slot

trigger:
  branches:
    include:
    - canary

stages:
  - stage: Trigger
    displayName: Trigger Web Deployment
    jobs:
    - job: Trigger
      steps:
      - bash: echo Trigger Deploy to Canary Web Slot