name: Documentation Feature Request
description: Suggest an improvement for Arc Jumpstart documentation
title: "[Docs Feature]: "
labels: ["Feature-Request", "Documentation", "Needs-Triage"]
projects: ["Azure/638"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a documentation improvement!

        If your feature request is related to code and/or functionality of a Jumpstart solution, we kindly ask you to submit it in our [source code repository](https://github.com/microsoft/azure_arc).

        The intent of this "Feature Request" template is to address feature requests related to the Arc Jumpstart documents. The Arc Jumpstart team does not handle and/or support Azure Arc upstream core product related features and will try to assist on a best effort basis. For a core product feature request/feedback, please submit through [general feedback](https://feedback.azure.com).
  - type: checkboxes
    id: doc-category
    attributes:
      label: Documentation Category
      description: Which area of documentation does this request relate to?
      options:
        - label: Jumpstart ArcBox
        - label: Jumpstart HCIBox
        - label: Jumpstart Agora
        - label: A specific Jumpstart scenario
        - label: Jumpstart Drops
        - label: Something else
  - type: textarea
    id: feature-description
    attributes:
      label: Documentation Need
      description: Describe what documentation you'd like to see added or improved
      placeholder: Example - "We need better documentation about configuring custom settings in ArcBox deployments"
    validations:
      required: true
  - type: input
    id: related-page
    attributes:
      label: Related Documentation Page
      description: If this relates to an existing page, please provide the URL
      placeholder: ex. https://jumpstart.azure.com/azure_jumpstart_arcbox/
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help us understand your documentation request
      placeholder: Include any examples, screenshots, or related resources
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct and Licensing
      description: By submitting this feature request, you agree to follow our [Code of Conduct](https://github.com/Azure/arc_jumpstart_docs/blob/main/CODE_OF_CONDUCT.md) and the project's [MIT license](https://github.com/microsoft/azure_arc/blob/main/LICENSE-CODE).
      options:
        - label: I agree to follow this project's Code of Conduct and Licensing terms.
          required: true