extends: existence
message: "In general, don't hyphenate '%s'."
link:  https://learn.microsoft.com/style-guide/a-z-word-list-term-collections/a/auto
ignorecase: true
level: error
action:
  name: convert
  params:
    - simple
tokens:
  - 'auto-\w+'
