extends: existence
message: "Don't use end punctuation in headings."
link:  https://learn.microsoft.com/style-guide/punctuation/periods
nonword: true
level: warning
scope: heading
action:
  name: edit
  params:
    - remove
    - '.?!'
tokens:
  - '[a-z][.?!](?:\s|$)'
