extends: existence
message: "Avoid using acronyms in a title or heading."
link:  https://learn.microsoft.com/style-guide/acronyms#be-careful-with-acronyms-in-titles-and-headings
level: warning
scope: heading
tokens:
  - '[A-Z]{2,4}'
