extends: existence
message: "'%s' doesn't need a hyphen."
link:  https://learn.microsoft.com/style-guide/punctuation/dashes-hyphens/hyphens
level: warning
ignorecase: false
nonword: true
action:
  name: edit
  params:
    - replace
    - '-'
    - ' '
tokens:
  - '\s[^\s-]+ly-'
