extends: existence
message: "Form a negative number with an en dash, not a hyphen."
link:  https://learn.microsoft.com/style-guide/numbers
nonword: true
level: error
action:
  name: edit
  params:
    - replace
    - '-'
    - '–'
tokens:
  - '\s-\d+\s'
