extends: existence
message: "Don't add -ly to an ordinal number."
link:  https://learn.microsoft.com/style-guide/numbers
level: error
action:
  name: edit
  params:
    - trim
    - ly
tokens:
  - firstly
  - secondly
  - thirdly
