extends: existence
message: "In most cases, use 'from' or 'through' to describe a range of numbers."
link: ' https://learn.microsoft.com/style-guide/numbers'
nonword: true
level: warning
tokens:
  - '\b\d+\s?[-–]\s?\d+\b'
