extends: existence
message: "Use 'to' instead of a dash in '%s'."
link:  https://learn.microsoft.com/style-guide/numbers
nonword: true
level: error
action:
  name: edit
  params:
    - replace
    - '[-–]'
    - 'to'
tokens:
  - '\b(?:AM|PM)\s?[-–]\s?.+(?:AM|PM)\b'
