extends: existence
message: "Don't use '%s' unless space is limited."
link:  https://learn.microsoft.com/style-guide/punctuation/dashes-hyphens/hyphens
ignorecase: true
level: warning
tokens:
  - '\w+- and \w+-'
