extends: existence
message: "Try to avoid using first-person plural like '%s'."
link:  https://learn.microsoft.com/style-guide/grammar/person#avoid-first-person-plural
level: warning
ignorecase: true
tokens:
  - we
  - we'(?:ve|re)
  - ours?
  - us
  - let's
