name: Canary Trigger

on:
  push:
    branches:
      - canary

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Obtain a GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN_NEW }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"
      - uses: actions/github-script@v6
        with:
          github-token: ${{ steps.githubAppAuth.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Azure',
              repo: 'arc_jumpstart_web',
              workflow_id: 'canary.yml',
              ref: 'newversion'
            })
